Case #1: [E, A]
Case #2: [R, I, R]
Case #3: [F, D, T]
Case #4: [Z, E, R, A]
Case #5: []
Case #6: [T, S, D, T, D, R, E, R]
Case #7: [W, R, Q, Q, A, W, I, R, D]
Case #8: [F]
Case #9: [Q, F, U, Q, E, R, F, D, Q]
Case #10: [R]
Case #11: [F]
Case #12: []
Case #13: [D, E, R, C, Q, D, D, W, D]
Case #14: [Y, A, Q, D, W, Q, Q, A, A]
Case #15: [A, E, Q, D, A, X, R, A, W]
Case #16: [H]
Case #17: [E, W]
Case #18: [S, D, A, A, T, E, F, A, D]
Case #19: []
Case #20: [D, A, D, R, A, A, R, Q, Z]
Case #21: [D, E, A, F, D, E, A, R, S]
Case #22: []
Case #23: [Z, Z, Z, Z, Z]
Case #24: [X, R, E, A, E]
Case #25: [W, I, S, F]
Case #26: [Y, F, A, Q, Y, F, R, F]
Case #27: [A, R, W, D, R, E, R, R, Y]
Case #28: [A, W, A, X, S, A, W, D, F]
Case #29: [W, S, R, W, H, W, F, W, F]
Case #30: [S, A, D, D]
Case #31: [N, E, R, E]
Case #32: [A, W, E, Y, D, S, Y, R]
Case #33: [Q, D, Q, S, C, D]
Case #34: [A, W, R, E, E]
Case #35: [R, D, R, G, R, R, E, S, D]
Case #36: [R, W]
Case #37: [Q, D, R, L, Q, F, R, E, E]
Case #38: []
Case #39: [S, F, Q, N, D, R, D, E, Q]
Case #40: [E, A, Q, M, F, R, D, E, R]
Case #41: [D, U, R, W]
Case #42: [Q, S, D]
Case #43: []
Case #44: [W, A, Q, Q, J, S, Q, A, A]
Case #45: [A, F]
Case #46: [E, Q, S, Q, S, S, Z, Q, S]
Case #47: [E, F, D]
Case #48: [I, F, F, F]
Case #49: [C, W, E, R, W, W, A, E, S]
Case #50: [Z, R, E, D]
Case #51: [S, F, F, G, Q, Q, R, R, E]
Case #52: [S, E, G, E, Q, Q, D, Q, E]
Case #53: [R, E, E]
Case #54: [S, R, A, F, B, R, A, Q, S]
Case #55: [E, E]
Case #56: [Y, E, D, S, E, S, R, E, R]
Case #57: [Q, S, T, W, F, W, Q, D, A]
Case #58: [A, W, A, R, E, N, E, S, S]
Case #59: [A, W, E, V, S, E, F]
Case #60: [Q, Z, W, Q]
Case #61: [A, D, A, W, D, E, E, S, V]
Case #62: [S, Q, A, C, Q]
Case #63: [E, D, S, Z, D, Z, R, R]
Case #64: [F, A, D, I, R, A, E, A, R]
Case #65: [S, S, R, R, R, R, G, S, A]
Case #66: [R, S, S, M, A, S, Q, D, A]
Case #67: [Q, Q, W, E, R, G, D, F, S]
Case #68: [F, O, E, F, E, S, W]
Case #69: [A]
Case #70: [F, S]
Case #71: []
Case #72: [S, R, E]
Case #73: []
Case #74: [A, R, W, F, P, D, D, A, Q]
Case #75: [R, A, W, W, W, F, T, E, A]
Case #76: [W, D, R, G, F, W, W, S, W]
Case #77: [Q, R, C, S, R, Q, R, D, W]
Case #78: []
Case #79: [R, F, D, F, E, W, P, E, E]
Case #80: [D, S, W, R, T, T, F, S]
Case #81: [D, N, R, W, R, F, D, W, S]
Case #82: [X]
Case #83: [E, E]
Case #84: [D]
Case #85: [S, X, R, A, D]
Case #86: [Y, W, A, S, D, Q, F, W, Q]
Case #87: [A, A, A, A, A, A, A, A, A, A]
Case #88: [R, A, S, D, S, E, E, N, D]
Case #89: [R]
Case #90: [A, W, W, W, W, C, Q, D, W]
Case #91: [E, D]
Case #92: [A, A, F, W, A, D, M, F, R]
Case #93: [S, Q, A, A, W, Q, R, I, W]
Case #94: [D, R, P, P, S]
Case #95: [V]
Case #96: [D, T, A, Q, D, E, S, E, W]
Case #97: [S, A]
Case #98: [Q, Q, E, S, A, Y, W, S, W]
Case #99: [R, F, X, Q, R, E, W, F, E]
Case #100: [R, I, D, Q, F, Q, F, F, E]
